# Generated by Django 5.2 on 2025-06-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="colorida",
            field=models.BooleanField(default=True, verbose_name="Impressão Colorida?"),
        ),
        migrations.AddField(
            model_name="category",
            name="resolucao",
            field=models.CharField(
                blank=True,
                help_text="Ex: 1200x1200 dpi",
                max_length=50,
                null=True,
                verbose_name="Resolução Máxima",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="uso_indicado",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Uso Indicado"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="velocidade_media_ppm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Velocidade Média (páginas por minuto)",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(max_length=100, verbose_name="Descrição"),
        ),
    ]
