# Generated by Django 5.2 on 2025-06-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_colorida_category_resolucao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="tipo",
            field=models.CharField(
                default=1, max_length=50, verbose_name="Tipo de Impressora"
            ),
            preserve_default=False,
        ),
    ]
