# Generated by Django 5.2 on 2025-06-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_category_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="resolucao",
        ),
        migrations.RemoveField(
            model_name="category",
            name="uso_indicado",
        ),
        migrations.AlterField(
            model_name="category",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("laser", "Laser"),
                    ("jato_tinta", "Jato de Tinta"),
                    ("matricial", "Matricial"),
                    ("3d", "3D"),
                    ("termo", "Térmica"),
                ],
                default="laser",
                max_length=20,
                verbose_name="Tipo de Impressora",
            ),
        ),
    ]
