# Generated by Django 5.2 on 2025-06-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RG", "RG"),
                            ("CPF", "CPF"),
                            ("CNH", "CNH"),
                            ("PASSAPORTE", "Passaporte"),
                            ("TIT_ELEITOR", "Título de Eleitor"),
                            ("CTPS", "Carteira de Trabalho"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                ("numero", models.CharField(max_length=30, verbose_name="Número")),
                (
                    "orgao_emissor",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Órgão Emissor",
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Emissão"
                    ),
                ),
                (
                    "validade",
                    models.DateField(blank=True, null=True, verbose_name="Validade"),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["id"],
            },
        ),
    ]
