# Generated by Django 5.2 on 2025-06-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("velocidade", models.IntegerField(verbose_name="Velocidade")),
                (
                    "resolucao",
                    models.CharField(max_length=50, verbose_name="Resolução"),
                ),
            ],
            options={
                "verbose_name": "Tipo",
                "verbose_name_plural": "Tipos",
                "ordering": ["id"],
            },
        ),
    ]
